# Generated by Django 2.0.3 on 2018-05-05 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retroboard', '0002_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='parent_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='retroboard.Board'),
        ),
        migrations.AddField(
            model_name='delta',
            name='parent_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='retroboard.Board'),
        ),
        migrations.AddField(
            model_name='positive',
            name='parent_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='retroboard.Board'),
        ),
    ]
